// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrunSatisPortali.Data;

#nullable disable

namespace UrunSatisPortali.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216090452_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UrunSatisPortali.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UrunSatisPortali.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çanta"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Cüzdan"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Aksesuar"
                        });
                });

            modelBuilder.Entity("UrunSatisPortali.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageUrl");

                    b.Property<int>("Stok")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Modern ve soyut desenli bez çanta.",
                            Ad = "Bez Çanta - Soyut Turuncu",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\1.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Canlı limon desenli yazlık çanta.",
                            Ad = "Bez Çanta - Limonlu",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\2.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Sanatsal el figürlü tasarım.",
                            Ad = "Bez Çanta - Yeşil Eller",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\3.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Mavi dalgalı desenli şık çanta.",
                            Ad = "Bez Çanta - Mavi Dalgali",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\4.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Siyah beyaz illüstrasyon baskılı.",
                            Ad = "Bez Çanta - İllüstrasyon",
                            CategoryId = 1,
                            Fiyat = 180m,
                            ResimYolu = "\\images\\products\\5.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Sade siyah üzerinde beyaz detaylar.",
                            Ad = "Siyah Çanta - Minimal",
                            CategoryId = 1,
                            Fiyat = 200m,
                            ResimYolu = "\\images\\products\\6.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Yumuşak pastel tonlarda tasarım.",
                            Ad = "Pastel Çanta - Pembe",
                            CategoryId = 1,
                            Fiyat = 160m,
                            ResimYolu = "\\images\\products\\7.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Eğlenceli muz desenli çanta.",
                            Ad = "Sarı Çanta - Muzlu",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\8.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Klasik dikey çizgili tasarım.",
                            Ad = "Çizgili Çanta",
                            CategoryId = 1,
                            Fiyat = 140m,
                            ResimYolu = "\\images\\products\\9.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Geometrik şekillerle modern stil.",
                            Ad = "Geometrik Çanta",
                            CategoryId = 1,
                            Fiyat = 170m,
                            ResimYolu = "\\images\\products\\10.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Hakiki deri kahverengi cüzdan.",
                            Ad = "Deri Cüzdan - Kahve",
                            CategoryId = 2,
                            Fiyat = 450m,
                            ResimYolu = "\\images\\products\\11.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Klasik siyah deri cüzdan.",
                            Ad = "Deri Cüzdan - Siyah",
                            CategoryId = 2,
                            Fiyat = 450m,
                            ResimYolu = "\\images\\products\\12.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "Minimalist mavi kartlık.",
                            Ad = "Kartlık - Mavi",
                            CategoryId = 2,
                            Fiyat = 120m,
                            ResimYolu = "\\images\\products\\13.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "El yapımı örgü anahtarlık.",
                            Ad = "Anahtarlık - Örgü",
                            CategoryId = 3,
                            Fiyat = 50m,
                            ResimYolu = "\\images\\products\\14.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "Trend balıkçı şapkası.",
                            Ad = "Şapka - Balıkçı",
                            CategoryId = 3,
                            Fiyat = 220m,
                            ResimYolu = "\\images\\products\\15.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "Sevimli kaktüs desenleri.",
                            Ad = "Bez Çanta - Kaktüs",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\16.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 17,
                            Aciklama = "Gezegen ve yıldız temalı.",
                            Ad = "Bez Çanta - Uzay",
                            CategoryId = 1,
                            Fiyat = 160m,
                            ResimYolu = "\\images\\products\\17.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 18,
                            Aciklama = "Kedi severler için özel tasarım.",
                            Ad = "Bez Çanta - Kedili",
                            CategoryId = 1,
                            Fiyat = 155m,
                            ResimYolu = "\\images\\products\\18.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 19,
                            Aciklama = "Bahar esintili çiçek desenli.",
                            Ad = "Bez Çanta - Çiçekli",
                            CategoryId = 1,
                            Fiyat = 150m,
                            ResimYolu = "\\images\\products\\19.jpg",
                            Stok = 50
                        },
                        new
                        {
                            Id = 20,
                            Aciklama = "Motivasyon sözleri içeren baskı.",
                            Ad = "Bez Çanta - Tipografi",
                            CategoryId = 1,
                            Fiyat = 145m,
                            ResimYolu = "\\images\\products\\20.jpg",
                            Stok = 50
                        });
                });

            modelBuilder.Entity("UrunSatisPortali.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrunSatisPortali.Models.OrderDetail", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrunSatisPortali.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.OrderHeader", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.Product", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.ShoppingCart", b =>
                {
                    b.HasOne("UrunSatisPortali.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("UrunSatisPortali.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrunSatisPortali.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
